// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class AirDay
{
    public int AirDayId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Anime> Animes { get; set; } = new List<Anime>();
}