// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Anime
{
    public int AnimeId { get; set; }

    public int SeasonKey { get; set; }

    public int MediaTypeKey { get; set; }

    public int OriginalSourceKey { get; set; }

    public int? AirDayKey { get; set; }

    public string Title { get; set; }

    public int Episodes { get; set; }

    public string Studio { get; set; }

    public DateTime? OnAir { get; set; }

    public DateTime? OffAir { get; set; }

    public string Sypnosis { get; set; }

    public decimal? MalScore { get; set; }

    public int? MalRank { get; set; }

    public string Genre { get; set; }

    public string Poster { get; set; }

    public int EpisodeTimeMins { get; set; }

    public DateTimeOffset LastSynced { get; set; }

    public int PullCount { get; set; }

    public DateTimeOffset LastModified { get; set; }

    public virtual AirDay AirDayKeyNavigation { get; set; }

    public virtual MediaType MediaTypeKeyNavigation { get; set; }

    public virtual OriginalSource OriginalSourceKeyNavigation { get; set; }

    public virtual Season SeasonKeyNavigation { get; set; }

    public virtual ICollection<TrackedAnime> TrackedAnimes { get; set; } = new List<TrackedAnime>();
}