// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class AniTrakContext : DbContext
{
    public AniTrakContext(DbContextOptions<AniTrakContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AirDay> AirDays { get; set; }

    public virtual DbSet<Anime> Animes { get; set; }

    public virtual DbSet<MediaType> MediaTypes { get; set; }

    public virtual DbSet<OriginalSource> OriginalSources { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<TrackedAnime> TrackedAnimes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<WatchStatus> WatchStatuses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AirDay>(entity =>
        {
            entity.HasKey(e => e.AirDayId).HasName("PK__AirDay__9AB7FA9DA28FB5F3");

            entity.ToTable("AirDay");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Anime>(entity =>
        {
            entity.HasKey(e => e.AnimeId).HasName("PK__tmp_ms_x__AF82112AA7FE9F12");

            entity.ToTable("Anime");

            entity.Property(e => e.Genre)
                .HasMaxLength(400)
                .IsUnicode(false);
            entity.Property(e => e.LastModified).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastSynced).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.MalScore).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.OffAir).HasColumnType("datetime");
            entity.Property(e => e.OnAir).HasColumnType("datetime");
            entity.Property(e => e.Poster)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Studio)
                .HasMaxLength(400)
                .IsUnicode(false);
            entity.Property(e => e.Sypnosis).IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.AirDayKeyNavigation).WithMany(p => p.Animes)
                .HasForeignKey(d => d.AirDayKey)
                .HasConstraintName("FK_Anime_AirDay");

            entity.HasOne(d => d.MediaTypeKeyNavigation).WithMany(p => p.Animes)
                .HasForeignKey(d => d.MediaTypeKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Anime_MediaType");

            entity.HasOne(d => d.OriginalSourceKeyNavigation).WithMany(p => p.Animes)
                .HasForeignKey(d => d.OriginalSourceKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Anime_OriginalSource");

            entity.HasOne(d => d.SeasonKeyNavigation).WithMany(p => p.Animes)
                .HasForeignKey(d => d.SeasonKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Anime_Season");
        });

        modelBuilder.Entity<MediaType>(entity =>
        {
            entity.HasKey(e => e.MediaTypeId).HasName("PK__MediaTyp__0E6FCB720849329A");

            entity.ToTable("MediaType");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OriginalSource>(entity =>
        {
            entity.HasKey(e => e.OriginalSourceId).HasName("PK__Original__FE22D09EA2856408");

            entity.ToTable("OriginalSource");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.HasKey(e => e.SeasonId).HasName("PK__Season__C1814E387110EB95");

            entity.ToTable("Season");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TrackedAnime>(entity =>
        {
            entity.HasKey(e => e.TrackedAnimeId).HasName("PK__tmp_ms_x__EDDD77D3BD78619F");

            entity.ToTable("TrackedAnime");

            entity.Property(e => e.LastModified).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastWatched).HasColumnType("datetime");
            entity.Property(e => e.Progress).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.StartedWatching).HasColumnType("datetime");
            entity.Property(e => e.StoppedWatching).HasColumnType("datetime");

            entity.HasOne(d => d.AnimeKeyNavigation).WithMany(p => p.TrackedAnimes)
                .HasForeignKey(d => d.AnimeKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrackedAnime_Anime");

            entity.HasOne(d => d.UserKeyNavigation).WithMany(p => p.TrackedAnimes)
                .HasForeignKey(d => d.UserKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrackedAnime_User");

            entity.HasOne(d => d.WatchStatusKeyNavigation).WithMany(p => p.TrackedAnimes)
                .HasForeignKey(d => d.WatchStatusKey)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrackedAnime_WatchStatus");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__tmp_ms_x__1788CC4C5EA0DC52");

            entity.ToTable("User");

            entity.Property(e => e.AuthZeroId)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LastSync).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Pfp)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WatchStatus>(entity =>
        {
            entity.HasKey(e => e.WatchStatusId).HasName("PK__WatchSta__04C0987AE012E0B1");

            entity.ToTable("WatchStatus");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}