// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class TrackedAnime
{
    public int TrackedAnimeId { get; set; }

    public int UserKey { get; set; }

    public int AnimeKey { get; set; }

    public int WatchStatusKey { get; set; }

    public DateTime? StartedWatching { get; set; }

    public DateTime? StoppedWatching { get; set; }

    public DateTime? LastWatched { get; set; }

    public int EpisodesWatched { get; set; }

    public DateTimeOffset LastModified { get; set; }

    public bool IsDeleted { get; set; }

    public decimal Progress { get; set; }

    public int TimeWatchedMins { get; set; }

    public virtual Anime AnimeKeyNavigation { get; set; }

    public virtual User UserKeyNavigation { get; set; }

    public virtual WatchStatus WatchStatusKeyNavigation { get; set; }
}