// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTimeOffset LastSync { get; set; }

    public string AuthZeroId { get; set; }

    public string Pfp { get; set; }

    public virtual ICollection<TrackedAnime> TrackedAnimes { get; set; } = new List<TrackedAnime>();
}