// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class WatchStatus
{
    public int WatchStatusId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<TrackedAnime> TrackedAnimes { get; set; } = new List<TrackedAnime>();
}