CREATE TABLE [dbo].[Anime]
(
	[AnimeId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [SeasonKey] INT NOT NULL, 
    [MediaTypeKey] INT NOT NULL, 
    [OriginalSourceKey] INT NOT NULL, 
    [AirDayKey] INT NULL, 
    [Title] VARCHAR(200) NOT NULL, 
    [Episodes] INT NOT NULL, 
    [Studio] VARCHAR(400) NULL, 
    [OnAir] DATETIME NULL, 
    [OffAir] DATETIME NULL, 
    [Sypnosis] VARCHAR(MAX) NULL, 
    [MalScore] DECIMAL NULL, 
    [MalRank] INT NULL, 
    [Genre] VARCHAR(400) NULL, 
    [Poster] VARCHAR(200) NOT NULL, 
    [EpisodeTimeMins] INT NOT NULL DEFAULT 0, 
    [LastSynced] DATETIMEOFFSET NOT NULL DEFAULT GETDATE(), 
    [PullCount] INT NOT NULL DEFAULT 0, 
    [LastModified] DateTimeOffset NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [FK_Anime_Season] FOREIGN KEY ([SeasonKey]) REFERENCES [Season]([SeasonId]),
    CONSTRAINT [FK_Anime_MediaType] FOREIGN KEY ([MediaTypeKey]) REFERENCES [MediaType]([MediaTypeId]),
    CONSTRAINT [FK_Anime_OriginalSource] FOREIGN KEY ([OriginalSourceKey]) REFERENCES [OriginalSource]([OriginalSourceId]),
    CONSTRAINT [FK_Anime_AirDay] FOREIGN KEY ([AirDayKey]) REFERENCES [AirDay]([AirDayId]),
)
