CREATE TABLE [dbo].[User]
(
	[UserId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Username] VARCHAR(100) NOT NULL, 
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [LastSync] DATETIMEOFFSET NOT NULL DEFAULT GETDATE(), 
    [AuthZeroId] VARCHAR(500) NULL, 
    [Pfp] VARCHAR(200) NULL
)
